spring.application.name=CouponRush

spring.config.import=optional:classpath:application-secret.properties
spring.datasource.url=jdbc:mysql://localhost:3306/couponrush
spring.jpa.hibernate.ddl-auto=validate

jwt.expiration=3600000

spring.data.redis.host=localhost
spring.data.redis.port=6379